image: Visual Studio 2017
test: off
cache:
- tools -> build.cake

build_script:
  - ps: .\build.ps1 -Target "Deploy"

artifacts:
  - path: 'artifacts\*.nupkg'

notifications:
  - provider: Slack
    incoming_webhook:
      secure: RnB921N0BobZCGc3kqxia5ttdkLGyDttxrnTrWcyUzjZrsXnsvyLYVy1cxwszb2yDnrX4WT2FCEF2Vz4teksx8phJ7eDxo+5BnxsQJGLGnA=
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true